version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
#      - ./mysql-data:/var/lib/mysql
    networks:
      hjimi:
        ipv4_address: 172.16.1.2


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    networks:
      hjimi:
        ipv4_address: 172.16.1.3

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      hjimi:
        ipv4_address: 172.16.1.4

  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
    networks:
      hjimi:
        ipv4_address: 172.16.1.5

networks:
  hjimi:
    external: true

volumes:
  mysqldata:
    name: mysqldata
    external: true
